---
name: 🚀 Umbraco Uno Issue
description: "Have a problem with Umbraco Uno? Missing a feature? Lets us know!"
labels: "category/uno"
body:
- type: textarea
  id: "description"
  attributes:
    label: "Issue description"
    description: "Write a summary of the issue you want to report."
  validations:
    required: true